export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const IT_SUPPORT_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IT_SUPPORT!;
export const IT_SUPPORT_ASSIGNEE_ID =
  process.env.NEXT_PUBLIC_APPWRITE_ASSIGNEE_ID_IT_SUPPORT!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
